### ISSUE TITLE
Name collision: service_server

### ISSUE THREAD

**Issue by peci1** [StefanFabian/ros_babel_fish#3]
The `service_server` example executable name is so general that it collides with another `service_server` executable provided by package [nimbro_service_transport](https://github.com/AIS-Bonn/nimbro_network/blob/7e1de20c8fb33fb1bf22ab9a8c4e93d098b9c4a3/nimbro_service_transport/CMakeLists.txt#L33).

Could you please rename the executable (and probably `service_client`) to e.g. `babel_service_server` or something more specific?

This is probably not a big problem if you build your workspace using catkin tools (`catkin build`) or `catkin_make_isolated`, but if you use the standard `catkin_make`, it doesn't support multiple targets with the same names.

**Comment by StefanFabian** [comment]
Thank you for bringing this to my attention.
We are using `catkin build` so I wasn't aware of that limitation.
I will update the target names.

**Comment by peci1** [comment]
Thanks.

**Comment by StefanFabian** [comment]
According to [this](https://github.com/ros-industrial/ros_industrial_issues/issues/8) only the target names have to be unique and the executables can be renamed to exclude the prefix.
This is the approach I'm going to use.
I will also rename the tests just to be sure.

**Comment by peci1** [comment]
You're right, changing the target names should be enough. I can test the fix when you release it.

**Comment by StefanFabian** [comment]
Didn't know writing "fix #N" in a commit message autocloses an issue.
Anyway, can you confirm the issue is fixed by that commit?

**Comment by peci1** [comment]
Yes, it works. Thanks!
